config_data:
    dataset_type: Datasetv3
    train_filepath:
      - name: torchmd
        path: /XXX/nb_decoys_MD_300K_200step_0.1gamma_1timestep_24_05_05_17_00_w_pdbid.csv
        weight: 1
        loss_weight: 1
      - name: esmflow200
        path: /XXX/nb_train_esmflow_2071_all_95_0510_filtered_w_pdbid.csv
        weight: 1
        loss_weight: 1
      - name: modeller
        path: /XXX/nb_train_modeller_2071_all_95_0430_w_pdbid.csv
        weight: 1
        loss_weight: 1
    valid_filepath: /XXX/model_zoo_nb_no4_95_testset_0522.csv,/XXX/model_zoo_nb_no8_95_testset_0522.csv
    test_filepath: /XXX/af3_nb88_0524.csv,/XXX/nb88_shot100_self_0524.csv,/XXX/nb88_shot100_esmflow_0524.csv
    max_ba: 1
    max_size: 8192
    min_num_res: 48
    max_num_atoms: 12288
    max_num_nn: 64
    interface_cut: 225
    trn_batch_size: 32
    val_batch_size: 1
    num_workers: 7
    prefetch_factor: 16
    aa_features: phi,psi,aas20,blosum62,rel_pos,meiler,usr
    debug: False
    pdb_fpath_col: pred_path
    label_col: RMSD_CA
    chain_col: chain
    cdr3_col: CDR3_RMSD_CA
#    rmsd_threshold: 0.01
    cdr3_threshold: 0.05
    rmsd_scale:
      - target: RMSD_CA
        scale_temp: 0.5
        scale_order: 1
      - target: CDR3_RMSD_CA
        scale_temp: 0.5
        scale_order: 1
    ca_only: True
    screener:
      - class: UpperboundScreener
        name: RMSD_CA
        upperbound: 5
      - class: UpperboundScreener
        name: CDR3_RMSD_CA
        upperbound: 10
    self_analyze:
      - target: RMSD_CA
        bin: [0,0.5,0.8,1.1,1.4,1.7,2.0,2.4,2.8,3.2,3.6,4.0,200000]
      - target: CDR3_RMSD_CA
        bin: [0,0.6,1.0,1.4,1.8,2.2,2.6,3.0,3.5,4.0,4.5,5.0,5.5,6.0,7.0,8.0,100000]
    fast_warm_up_set:
      target: CDR3_RMSD_CA
      size_ratio: 0.05


config_model:
    model_name: ScoreModel
    nf:
      N0: 30
      N1: 32
    hat:
      Ns: 32
      Nh: 2
      Nk: 3
      nn: 8,16,32,64
      n_layer_per_block: 8
    rlp:
      N0: 32
      N1: 32
      Nh: 4
    dm:
      N0: 32
      N0_: 64
      N1: 32
      N2: 16
    att:
      N0: 16
    fc1:
      N1: 16
    fc2:
      N0: 16
      N1: 8
    fr_bn: False
    id_enable: True
    id:
      N0: 59
      N1: 64
      N2: 32
    id_bn: True
    out: 1
    out_weight: [1]
    sigmoid_index: []
    init_model: 'none'

config_runtime:
    seed: 8
    device: 'cuda'
    num_epochs: 100000000    # not work, controlled by max_epochs in args
    learning_rate: 0.0001    # not work, controlled by max_lr of scheduler
    acc_grad: 1
    optimizer: adam
    wd: 0.00000001
    clip: 0.0
    resume_from_ckpt: False
    ema_start_epoch: 10
    ema_decay: 0.9999
    use_fsdp: False
    loss_fn:
        - type: ranknet
          output: 0
          target: CDR3_RMSD_CA_scale
          weight: 1
          start_iter: 0