apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nb-refinement-0-2-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.13, pipelines.kubeflow.org/pipeline_compilation_time: '2024-04-19T04:52:34.021143',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "An end to end pipeline
      setting including hyperparameter tuning, train and inference.", "inputs": [{"name":
      "device_id"}, {"name": "interval"}, {"name": "frac"},
      {"name": "logpath"}, {"name": "gpu_nums"}, {"name":
      "image"}], "name": "esmflow-infer-0"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.13}
spec:
  entrypoint: nb-refinement-0-2
  templates:
  - name: nb-refinement-0
    resource:
      action: create
      successCondition: status.replicaStatuses.Launcher.succeeded==1
      failureCondition: status.replicaStatuses.Launcher.failed==1
      setOwnerReference: true
      manifest: |
        apiVersion: kubeflow.org/v1
        kind: MPIJob
        metadata:
          generateName: nb-refinement-0-
        spec:
          mpiReplicaSpecs:
            Launcher:
              replicas: 1
              template:
                metadata:
                  annotations:
                    sidecar.istio.io/inject: 'false'
                  labels:
                    file-mount: 'true'
                spec:
                  containers:
                  - command:
                    - /bin/sh
                    - -cl
                    - 'mpirun -np 1 -tag-output --allow-run-as-root
                      -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x
                      PATH -mca pml ob1 -mca btl ^openib bash ./run_train_sin_k8s_trial6.sh
                      {{inputs.parameters.device_id}} 
                      > {{inputs.parameters.logpath}} 2>&1  # please keep the param ''-np'' same with ''replicas'' in ''Worker''

                      '
                    image: '{{inputs.parameters.image}}'
                    imagePullPolicy: Always
                    name: mpi-launcher
                    resources:
                      limits:
                        cpu: 1
                        memory: 1Gi
                    workingDir: /nfs_beijing_ai/jinxian/rama-scoring1.3.0/bin/sin_equiformerV2_train_shs/
            Worker:
              replicas: 1
              template:
                metadata:
                  annotations:
                    sidecar.istio.io/inject: 'false'
                  labels:
                    file-mount: 'true'
                    # user-mount: 'true'
                spec:
                  containers:
                  - image: '{{inputs.parameters.image}}'
                    imagePullPolicy: Always
                    name: mpi-worker
                    resources:
                      limits:
                        cpu: 5
                        memory: 500Gi
                        nvidia.com/gpu: '{{inputs.parameters.gpu_nums}}'
                    volumeMounts:
                    - mountPath: /dev/shm
                      name: ziqiao
                  nodeSelector:
                    gpu.device: a100
                  tolerations:
                  # - effect: NoSchedule
                  #   key: role
                  #   operator: Equal
                  #   value: threeweek
                  # - effect: NoSchedule
                  #   key: role
                  #   operator: Equal
                  #   value: m1b
                  - effect: NoSchedule
                    key: role
                    operator: Equal
                    value: mpu
                  # - effect: NoSchedule
                  #   key: role
                  #   operator: Equal
                  #   value: algo2
                  volumes:
                  - emptyDir:
                      medium: Memory
                      sizeLimit: 1Gi
                    name: ziqiao
          runPolicy:
            cleanPodPolicy: Running
            ttlSecondsAfterFinished: 30
          slotsPerWorker: 1
    inputs:
      parameters:
      - {name: device_id}
      - {name: gpu_nums}
      - {name: image}
      - {name: logpath}
    outputs:
      parameters:
      - name: nb-refinement-0-manifest
        valueFrom: {jsonPath: '{}'}
      - name: nb-refinement-0-name
        valueFrom: {jsonPath: '{.metadata.name}'}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.13
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: nb-refinement-0-2
    inputs:
      parameters:
      - {name: device_id}
      - {name: gpu_nums}
      - {name: image}
      - {name: logpath}
    dag:
      tasks:
      - name: nb-refinement-0
        template: nb-refinement-0
        arguments:
          parameters:
          - {name: device_id, value: '{{inputs.parameters.device_id}}'}
          - {name: gpu_nums, value: '{{inputs.parameters.gpu_nums}}'}
          - {name: image, value: '{{inputs.parameters.image}}'}
          - {name: logpath, value: '{{inputs.parameters.logpath}}'}
  arguments:
    parameters:
    - {name: device_id}
    - {name: logpath}
    - {name: gpu_nums}
    - {name: image}
  serviceAccountName: pipeline-runner
