config_data:
    dataset_type: NB
    
    train_filepath:
      - name: esmflow_modeller_openmm_torchMD
        path: /nfs_beijing_ai/jinxian/rama-scoring1.3.0/dataset/datasets/NB_train_dataset_train_all_decoys_with_RMSD.csv
        weight: 1
        loss_weight: 1
      #      - name: torchmd95
      #        path: /pfs_beijing/sunyiwu/model_selection/modeller/notebooks/csvs/nb_train_torchMD_2071_all_95_0511_w_pdbid.csv    # torch MD with 95 metrics
      #        weight: 1
      #        loss_weight: 1
      #      - name: esmflow20
      #        path: /pfs_beijing/sunyiwu/structure_pretraining/xtrimo_eigenfold/rama-scoring/notebooks/csvs/nb_train_esmflow_2071_41080_0423_filtered_w_pdbid.csv  # esm 20
      #        weight: 10
      #        loss_weight: 1
      #      - name: Yakun
      #        path: /nfs_beijing_ai/ziqiao-2/tmp/YakunDecoysPreprocessOutput240508/decoy_trainset_csv/vhh_a_l_l_decoys_1835_feature_metric.csv    # Yakun's decoys
      #        weight: 2
      #        loss_weight: 1
      # - name: esmflow200
      #   path: /pfs_beijing/sunyiwu/structure_pretraining/xtrimo_eigenfold/rama-scoring/notebooks/csvs/nb_train_esmflow_2071_all_95_0510_filtered_w_pdbid.csv   # esm
      #   weight: 1
      #   loss_weight: 1
      # - name: modeller
      #   path: /pfs_beijing/sunyiwu/model_selection/modeller/notebooks/csvs/nb_train_modeller_2071_all_95_0430_w_pdbid.csv   # modeller
      #   weight: 1
      #   loss_weight: 1
      #      - name: MD300K
      #        path: /pfs_beijing/sunyiwu/model_selection/modeller/notebooks/csvs/nb_train_openmm_300K_2071_all_95_0510_w_pdbid.csv    # Zongyang's MD
      #        weight: 1
      #        loss_weight: 1
      #      - name: MD450K
      #        path: /pfs_beijing/sunyiwu/model_selection/modeller/notebooks/csvs/nb_train_openmm_450K_2071_all_95_0510_w_pdbid.csv
      #        weight: 1
      #        loss_weight: 1
      #      - name: MD600K
      #        path: /pfs_beijing/sunyiwu/model_selection/modeller/notebooks/csvs/nb_train_openmm_600K_2071_all_95_0510_w_pdbid.csv
      #        weight: 1
      #        loss_weight: 1
      #    valid_filepath: /pfs_beijing/sunyiwu/structure_pretraining/xtrimo_eigenfold/rama-scoring/notebooks/csvs/model_zoo_nb_no4_95_testset.csv,/pfs_beijing/sunyiwu/structure_pretraining/xtrimo_eigenfold/rama-scoring/notebooks/csvs/model_zoo_nb_no8_95_testset.csv
    valid_filepath: /nfs_beijing_ai/jinxian/rama-scoring1.3.0/dataset/datasets/NB88_scoring_model.csv
    test_filepath: /nfs_beijing_ai/jinxian/rama-scoring1.3.0/dataset/datasets/NB25.csv
    sample_num: -1 # if you need all data, set sample_num = -1
    valid_head: 100 # get the valid data num from the train data
    trn_batch_size: 8
    val_batch_size: 1
    min_num_workers: 4
    num_workers: 4
    prefetch_factor: 8
    debug: False
    pdb_fpath_col: pred_path
    label_col: RMSD_CA
    chain_col: chain
    cdr3_col: CDR3_RMSD_CA
#    rmsd_threshold: 0.01
    cdr3_threshold: 0.05
    rmsd_scale:
      - target: RMSD_CA
        scale_temp: 0.5
        scale_order: 1
      - target: CDR3_RMSD_CA
        scale_temp: 0.5
        scale_order: 1
    ca_only: True
    screener:
      - class: UpperboundScreener
        name: RMSD_CA
        upperbound: 5
      - class: UpperboundScreener
        name: CDR3_RMSD_CA
        upperbound: 10
#    down_sampling:
#      target: RMSD_CA
#      bin: [0,0.5,0.8,1.1,1.4,1.7,2.0,2.4,2.8,3.2,3.6,4.0,200000]
#      source: no4
#      probs: [0.01239669,0.12190083,0.25309917,0.22933884,0.14049587,0.05785124,0.06198347,0.04442149,0.02582645,0.01446281,0.02272727,0.01549587]
#      size_ratio: 0.1
#      target: CDR3_RMSD_CA
#      bin: [0,0.6,1.0,1.4,1.8,2.2,2.6,3.0,3.5,4.0,4.5,5.0,5.5,6.0,7.0,8.0,100000]
#      source: no4
#      probs: [0.03202479,0.12913223,0.08884298,0.13842975,0.10433884,0.10433884,0.05268595,0.09090909,0.05991736,0.04235537,0.02995868,0.01446281,0.02272727,0.02376033,0.03305785,0.03305785]
#      size_ratio: 0.1
    self_analyze:
      - target: RMSD_CA
        bin: [0,0.5,0.8,1.1,1.4,1.7,2.0,2.4,2.8,3.2,3.6,4.0,200000]
      - target: CDR3_RMSD_CA
        bin: [0,0.6,1.0,1.4,1.8,2.2,2.6,3.0,3.5,4.0,4.5,5.0,5.5,6.0,7.0,8.0,100000]
    fast_warm_up_set:
      target: CDR3_RMSD_CA
      size_ratio: 0.05


config_model:
    model_reload_path: False
    model_name: equiformer_v2
#    out: 1
#    out_weight: [1]
#    sigmoid_index: []
#    init_model: 'none'
    use_pbc: False
    regress_forces: True
    use_equivariant_block: True # 是否使用等变网络
    use_invariant_block: False # 是否使用不变网络
    use_KL_loss: False
    KL_loss_weight: 1
    otf_graph: True
    max_neighbors: 20
    max_radius: 9.0
    max_num_elements: 90
    max_num_atom_names: 37
    max_num_residues: 21

    num_layers: 4
    sphere_channels: 24
    attn_hidden_channels: 64              # [64, 96] This determines the hidden size of message passing. Do not necessarily use 96.
    num_heads: 2
    attn_alpha_channels: 32              # Not used when `use_s2_act_attn` is True.
    attn_value_channels: 8
    ffn_hidden_channels: 64
    norm_type: 'layer_norm_sh'    # ['rms_norm_sh', 'layer_norm', 'layer_norm_sh']

    lmax_list: [ 2 ]
    mmax_list: [ 2 ]
    grid_resolution: 14              # [18, 16, 14, None] For `None`, simply comment this line.

    num_sphere_samples: 32

    edge_channels: 32
    use_atom_edge_embedding: True
    share_atom_edge_embedding: False         # If `True`, `use_atom_edge_embedding` must be `True` and the atom edge embedding will be shared across all blocks.
    distance_function: 'gaussian'
    num_distance_basis: 512           # not used

    attn_activation: 'silu'
    use_s2_act_attn: False       # [False, True] Switch between attention after S2 activation or the original EquiformerV1 attention.
    use_attn_renorm: True        # Attention re-normalization. Used for ablation study.
    ffn_activation: 'silu'      # ['silu', 'swiglu']
    use_gate_act: False       # [True, False] Switch between gate activation and S2 activation
    use_grid_mlp: True        # [False, True] If `True`, use projecting to grids and performing MLPs for FFNs.
    use_sep_s2_act: True        # Separable S2 activation. Used for ablation study.

    alpha_drop: 0.1         # [0.0, 0.1]
    drop_path_rate: 0.05        # [0.0, 0.05]
    proj_drop: 0.0

    weight_init: 'uniform'    # ['uniform', 'normal']

config_runtime:
    seed: 13
    epoch: 100
    log_interval: 500 # log the train info each log_interval batch step
    log_interval_for_test: 4000 # log the test info each log_interval_for_test batch step
    
    weight_angle_decay_rate: 0.99
    device: 'cuda'
    num_epochs: 100000000    # not work, controlled by max_epochs in args
    learning_rate: 0.0001    # not work, controlled by max_lr of scheduler
    acc_grad: 1
    optimizer: adam
    wd: 0.00000001
    clip: 0.0
    resume_from_ckpt: False
    ema_start_epoch: 10
    ema_decay: 0.9999
    use_fsdp: False
    use_rmsd: True
    rmsd_loss_weight: 10
    use_CDR_loss: True
    use_cg_loss: True
    use_tran_mse_loss: False #False is use tran moudle and angle loss, or use tran mse loss
    tran_mse_loss_mean_or_sum: mean
    angle_loss_mean_or_sum: mean
    tran_loss_mean_or_sum: mean
    weight_tran: 0.01
    weight_angle: 10
    distmap_loss_mean_or_sum: mean
    distmap_loss_use_cdr_mask: False
    distmap_loss_weight: 1
    cdr1_loss_weight: 1
    cdr2_loss_weight: 1
    cdr3_loss_weight: 10
    no_cdr_loss_weight: 0.1
    cg_loss_weight: 0.05
    loss_fn:
        - type: magnitude_loss
          output: 0
          target: CDR3_RMSD_CA_scale
          weight: 1
          start_iter: 0