wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1731480940
    t:
      1:
      - 1
      - 55
      - 77
      3:
      - 13
      - 16
      4: 3.8.13
      5: 0.12.21
      8:
      - 5
architecture:
  desc: null
  value: equiformer2
epochs:
  desc: null
  value: 100
test_data_file:
  desc: null
  value: /nfs_beijing_ai/jinxian/rama-scoring1.3.0/dataset/datasets/model_zoo_nb_no4_95_testset_0522.csv
train_data_file:
  desc: null
  value: /nfs_beijing_ai/jinxian/rama-scoring1.3.0/dataset/datasets/NB_train_dataset_valid.csv
